version: '2'
services:
  ppmbsm:
    build:
      context: .
      dockerfile: Dockerfile.cdot
    environment:
      CVPEP_BSM_DEPOSIT_KEY: wydot-bsm-
      CVPEP_BSM_TOPIC: topic.OdeBsmJson
      K_AWS_SESSION_TOKEN: SessionToken
      K_AWS_EXPIRATIONN: Expiration
      HEADER_ACCEPT: application/json
      DEPOSIT_GROUP: group_cvpep_bsm
      DEPOSIT_BUCKET_NAME: ${DEPOSIT_BUCKET_NAME}
      DEPOSIT_KEY_NAME: ${DEPOSIT_ACCESS_KEY}
      K_AWS_ACCESS_KEY_ID: ${K_AWS_ACCESS_KEY_ID}
      API_ENDPOINT: ${API_ENDPOINT}
      HEADER_X_API_KEY: ${HEADER_X_API_KEY}
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_TYPE: ${KAFKA_TYPE}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}

    depends_on:
      - kafka