version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic.OdeBsmJson:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  s3d:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      HEADER_ACCEPT: ${HEADER_ACCEPT}
      HEADER_X_API_KEY: ${HEADER_X_API_KEY}
      DEPOSIT_BUCKET_NAME: ${DEPOSIT_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      DEPOSIT_KEY_NAME: ${DEPOSIT_KEY_NAME}
      DEPOSIT_TOPIC: ${DEPOSIT_TOPIC}
      DEPOSIT_GROUP: ${DEPOSIT_GROUP}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_EXPIRATION: ${AWS_EXPIRATION}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - kafka