version: '2'
services:
  s3d:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOOTSTRAP_SERVER: ${BOOTSTRAP_SERVER}
      API_ENDPOINT: ${API_ENDPOINT}
      DEPOSIT_TOPIC: ${DEPOSIT_TOPIC}
      DEPOSIT_GROUP: ${DEPOSIT_GROUP}
      DESTINATION: ${DESTINATION}
      DEPOSIT_BUCKET_NAME: ${DEPOSIT_BUCKET_NAME}
      REGION: ${REGION}
      DEPOSIT_KEY_NAME: ${DEPOSIT_KEY_NAME}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_EXPIRATION: ${AWS_EXPIRATION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      HEADER_ACCEPT: ${HEADER_ACCEPT}
      HEADER_X_API_KEY: ${HEADER_X_API_KEY}
      KAFKA_TYPE: ${KAFKA_TYPE}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}
      GOOGLE_APPLICATION_CREDENTIALS: '/google/gcp_service_account.json'
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/gcp_service_account.json d
      