#General Properties
#==================
groupId: ^project.groupId^
artifactId: ^project.artifactId^
version: ^project.version^
server.port: 8082

# Kafka properties
spring.kafka.bootstrap-servers: ${KAFKA_BROKER_IP:localhost}:9092
spring.kafka.consumer.group-id: ^project.artifactId^

# logging.level.org.apache.kafka: INFO
logging.level:
  root: INFO
# log4j.logger.kafka: OFF
# log4j.logger.org.apache.kafka: OFF
