name: Publish Java Package Tag

on:
  push:
    tags:
      - "*"

jobs:
  publish-java-package:
    uses: ./.github/workflows/artifact-publish.yml
    with:
      drop-snapshot: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}